trigger:
  branches:
    include:
      - main

variables:
  acrName: 'restaurantacr13022002.azurecr.io'
  imageName: 'backend'
  dockerfilePath: 'Dockerfile'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: Build and push backend image
  jobs:
  - job: BuildAndPush
    displayName: Docker build and push to ACR
    steps:

    - task: Docker@2
      displayName: Build and push to ACR
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: $(dockerfilePath)
        containerRegistry: 'acr-connection'
        tags: |
          $(Build.BuildId)
          latest

    - script: echo "Image pushed — $(acrName)/$(imageName):$(Build.BuildId)"
      displayName: Confirm image tag